### ISSUE TITLE
Generating binary files fails when a Padrino Rack app

### ISSUE THREAD

**Issue by Nyoho** [r7kamura/sitespec#12]
PadrinoでRackアプリを作った場合に、Content-type: image/png などのバイナリファイルを生成しようとすると https://github.com/Nyoho/sitespec-padrino-sample2/issues/1 のように失敗します。

```
Failures:

  1) Sitespec GET public/images/simple-image1.png Generate a static image public/images/simple-image1.png
     Failure/Error: pathname.write(response.body)

     Encoding::UndefinedConversionError:
       "\x89" from ASCII-8BIT to UTF-8
```

Pathname.write(response.body) がなぜか UTF-8 に変換しようとしているようです。

```ruby
module Sitespec
  class Artifact
    def generate_file
      puts path ; puts response.body.encoding
      pathname.binwrite(response.body)
    end
  end
end
```
と、writeをbinwirteにすれば正しく生成されます。

ところが、Sinatraでプロジェクトを作ってみると同じことをしても失敗しません。

比較のためにシンプルな Padrino と Sinatra のプロジェクトを作ってみました。
- Padrino https://github.com/Nyoho/sitespec-padrino-sample2
- Sinatra https://github.com/Nyoho/simple-sitespec-sinatra-test

どちらも、``rspec`` して ``binding.pry`` で止めたところで ``break Sitespec::Artifact#generate_file`` をしてチェックしてみましたが、どちらも画像のバイナリファイルのときは、``response.body.encoding`` は ``ASCII-8BIT`` でした。

write を binwrite としてしまう pull request を出すべきなのかとも思いますが、Sinatraではうまく動くので、Sinatraでうまく動く理由・Padrinoだとうまく動かない理由を知りたいところです。
ここまでご報告申し上げます。

**Comment by r7kamura** [comment]
今もう動かしてないんですが、https://github.com/r7kamura/blog がPadrino + Sitespecで動かしていて、これは画像も上手く生成していますね。特に困ったことはなかった。

このプロジェクトでは静的ファイルホスティングには   `use Rack::Static, urls: ["/images"]` とやっている模様です。そのサンプルのPadrinoのアプリでは、静的ファイルはどういうロジックでレスポンスとして返していますか？

**Comment by Nyoho** [comment]
サンプルのPadrinoアプリでは、静的ファイルは、``/public`` に置いてあるファイルをそのまま配信するという [Sinatraの仕様](http://www.sinatrarb.com/intro-ja.html#%E9%9D%99%E7%9A%84%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB(Static%20Files))をそのまま使っています。
ですので、https://github.com/Nyoho/sitespec-padrino-sample2/tree/master/public の ``/public`` に置いているものを直接 get するように spec ファイルを書いています。

**Comment by r7kamura** [comment]
手元で両方試してみて curl でリクエスト送ったりしてみましたが全然違いがわかりませんね…

**Comment by Nyoho** [comment]
試していただきありがとうございます! そうなんですよね。レスポンスも全く等しいように思えるのですが、Padrinoプロジェクトだけ Pathname.write でエラーが出るんですよね…

**Comment by r7kamura** [comment]
一応、session周りの出力はちょっと違いますね…。関係ないかとは思いますが…。RSpecで利用している `get` が何かリクエストヘッダを付けている可能性はあり、これに対応して挙動を変えているとか、そういう可能性はあります。

**Comment by r7kamura** [comment]
最近のRubyではもう見ることはほぼありませんが、昔は文字コードの挙動がグローバル変数で変わっていましたよね、`$KCODE` だったかな。昔はRailsがこれを勝手に変更したりしていたような気もします。

**Comment by Nyoho** [comment]
なるほど、その方向でPadrinoのソースを見たりしてみます。
ちなみにそちらのご環境でも同じwriteでのエラーが出ますか?

**Comment by r7kamura** [comment]
はい、エラーはPadrinoの方だけ出ました

**Comment by Nyoho** [comment]
ありがとうございます。
試しに、Padrinoの方を、r7kamuraさんの旧ブログのをまねして ``use Rack::Static, urls: ["/images"] `` して、``mv public/images .`` してみると、エラーが出なくなりました。

つまり Sinatra のデフォルトである /public の静的配信設定を Padrino がいじっている可能性があるという感じでしょうか。引き続き調べてみたいと思います。

**Comment by Nyoho** [comment]
あ、それはうそでした! specファイルの記述の public/ を取っていなかったので何もないことになってスルーしていただけでした。(ちゃんと表示を読まなければ汗汗)
それで、r7kamuraさんの旧ブログと特に同じように Rack::Static の設定をしても、同じ ``Pathname#write`` エラーが出たのでした。失礼いたしました。

じゃあr7kamuraさんの旧ブログと何が違うのかという話になりますね。なかなか手強いです。

**Comment by Nyoho** [comment]
徐々にSitespec固有の問題というわけでもない気がして参りましたし、Stackoverflowにでも質問を立ててみようかと思います!
